# Import functions from other test files
# Using importlib to import modules from the same directory
import importlib.util
import os

# Get the directory of this file
current_dir = os.path.dirname(os.path.abspath(__file__))

# Load prime module
prime_spec = importlib.util.spec_from_file_location("prime", os.path.join(current_dir, "prime.py"))
prime = importlib.util.module_from_spec(prime_spec)
prime_spec.loader.exec_module(prime)

# Load generator module
generator_spec = importlib.util.spec_from_file_location("generator", os.path.join(current_dir, "generator.py"))
generator = importlib.util.module_from_spec(generator_spec)
generator_spec.loader.exec_module(generator)


def get_cyclic_group_elements(g, P, order=None):
    """
    Get all elements of the cyclic group generated by g modulo P.
    
    Args:
        g: Generator
        P: Prime modulus
        order: Order of the subgroup (if None, uses P-1 for full group)
    
    Returns:
        List of all elements in the cyclic group: [g^0, g^1, g^2, ..., g^(order-1)] mod P
    """
    elements = []
    if order is None:
        order = P - 1
    
    for i in range(order):
        element = generator.modular_power(g, i, P)
        elements.append(element)
    
    return elements


def get_cyclic_groups(P):
    """
    Get all cyclic subgroups of the multiplicative group modulo P.
    
    If P-1 = q1^k1 * q2^k2 * ..., then for each prime factor qi,
    the cyclic subgroup is generated by g^((P-1)/qi) where g is a primitive root.
    
    Args:
        P: Prime number to analyze
    
    Returns:
        Dictionary containing:
        - 'is_prime': Boolean indicating if P is prime
        - 'p_minus_one': Value of P-1
        - 'factorization': Full factorization with powers: {q1: k1, q2: k2, ...}
        - 'factorization_str': String representation of (P-1) factorization
        - 'primitive_root': A primitive root g used to generate subgroups
        - 'cyclic_subgroups': Dictionary mapping each prime factor q to its subgroup
          Each subgroup contains: 'generator' (g^((P-1)/q)), 'order' (q^k), 'elements'
    
    Example:
        >>> result = get_cyclic_groups(7)
        >>> # P-1 = 6 = 2^1 * 3^1
        >>> # Subgroups: g^(6/2) and g^(6/3)
    """
    # Check if P is prime
    if not prime.is_prime(P):
        return {
            'is_prime': False,
            'error': f'{P} is not a prime number'
        }
    
    # Calculate P-1
    p_minus_one = P - 1
    
    # Get full factorization with powers
    factorization = generator.factorize(p_minus_one)
    
    # Get factorization string
    factorization_str = generator.format_factorization(p_minus_one)
    
    # Get prime factors (keys of factorization dict)
    prime_factors = generator.get_prime_factors(p_minus_one)
    
    # Find all primitive roots (generators of the full field)
    primitive_roots = generator.find_generators(P)
    if len(primitive_roots) == 0:
        return {
            'is_prime': True,
            'prime': P,
            'error': 'No primitive roots found'
        }
    
    # Use the first primitive root for computing subgroups
    g = primitive_roots[0]
    
    # Compute cyclic subgroups for each prime factor
    cyclic_subgroups = {}
    
    for q in prime_factors:
        # Calculate (P-1) / q
        divisor = p_minus_one // q
        
        # Generator of the subgroup: g^((P-1)/q)
        subgroup_generator = generator.modular_power(g, divisor, P)
        
        # Order of the subgroup: q^k where k is the power in factorization
        order = q ** factorization[q]
        
        # Get all elements of the subgroup
        elements = get_cyclic_group_elements(subgroup_generator, P, order)
        
        cyclic_subgroups[q] = {
            'prime_factor': q,
            'power': factorization[q],
            'generator': subgroup_generator,
            'order': order,
            'elements': elements
        }
    
    return {
        'is_prime': True,
        'prime': P,
        'p_minus_one': p_minus_one,
        'factorization': factorization,
        'factorization_str': factorization_str,
        'prime_factors': prime_factors,
        'primitive_root': g,
        'all_primitive_roots': primitive_roots,
        'num_primitive_roots': len(primitive_roots),
        'cyclic_subgroups': cyclic_subgroups
    }


if __name__ == "__main__":
    # Example usage
    test_primes = [23]
    
    print("=== Cyclic Groups of Prime Numbers ===\n")
    
    for P in test_primes:
        result = get_cyclic_groups(P)
        
        if not result['is_prime']:
            print(f"P = {P}: {result['error']}\n")
            continue
        
        print(f"P = {result['prime']}")
        print(f"  P-1 = {result['p_minus_one']}")
        print(f"  Factorization: {result['p_minus_one']} = {result['factorization_str']}")
        print(f"  All primitive roots (generators): {result['all_primitive_roots']}")
        print(f"  Number of primitive roots: {result['num_primitive_roots']}")
        print(f"  Primitive root used for subgroups: g = {result['primitive_root']}")
        print()
        
        # Print cyclic subgroups
        print("  Cyclic Subgroups:")
        for q in result['prime_factors']:
            subgroup = result['cyclic_subgroups'][q]
            print(f"    For prime factor q = {q} (power = {subgroup['power']}):")
            print(f"      Generator: g^((P-1)/{q}) = {result['primitive_root']}^({result['p_minus_one']}/{q}) = {subgroup['generator']}")
            print(f"      Order: {subgroup['order']}")
            print(f"      Elements: {subgroup['elements']}")
            print()

